# Change these first
owner: gekki-beep # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Panel
    url: https://pterodactyl.ifive-roleplay.fr/
    icon: https://i.imgur.com/51J6HuV.png
  - name: API Panel
    url: https://pterodactyl.ifive-roleplay.fr/api/client/
    icon: https://i.imgur.com/51J6HuV.png
  - name: API
    url: http://node04.ifive-community.fr:10003/ifive
    icon: https://i.imgur.com/51J6HuV.png
  - name: Node04
    url:  http://node04.ifive-community.fr/
    icon: https://i.imgur.com/51J6HuV.png
    expectedStatusCodes:
      - 404
      - 403
  - name: SQL01
    url: https://pterodactyl.ifive-roleplay.fr/pma
    icon: https://i.imgur.com/51J6HuV.png
  - name: Wiki
    url: https://wiki.ifive-community.fr
  - name: Grafana
    url: http://node04.ifive-community.fr:10004
    icon: https://i.imgur.com/51J6HuV.png
  - name: Discord
    url: https://discord.com/
  - name: Steam
    url: https://api.steampowered.com
    expectedStatusCodes:
      - 404
      - 406
    icon: https://www.pinclipart.com/picdir/middle/100-1003109_steam-clip-art.png
  - name: iFive FiveM
    check: "tcp-ping"
    url: node04.ifive-community.fr
    port: 30120
    icon: https://i.imgur.com/51J6HuV.png
  - name: CFX
    url: https://cfx.re/join/pzvm47
    icon: https://avatars.githubusercontent.com/u/25160833?s=280&v=4
  - name: API CFX
    url: https://status.cfx.re/api/v2/status.json
    icon: https://avatars.githubusercontent.com/u/25160833?s=280&v=4
    __dangerous__body_down_if_text_missing: "All Systems Operational"
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /status-page # where "repo" is your repository name
  name: Status Page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "Status Page - Yothann"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO   

i18n:
  footer: Monitoring
  activeIncidents: Incidents actifs
  allSystemsOperational: L'ensemble des systèmes sont opérationnels
  incidentReport: "Incident #$NUMBER →"
  activeIncidentSummary: Ouvert le $DATE avec $POSTS messages
  incidentTitle: Détails de l'incident $NUMBER
  incidentDetails: Détails de l'incident
  incidentFixed: Réparé
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert le
  incidentClosedAt: Fermé le
  incidentViewOnGitHub: Voir et s'abonner sur GitHub
  incidentCommentSummary: posté le $DATE par $AUTHOR
  incidentBack: ← Retour à tout les incidents
  pastIncidents: Anciens incidents
  pastIncidentsResolved: Résolu en $MINUTES minutes avec $POSTS messages
  liveStatus: Statut en direct
  overallUptime: "Temps de fonctionnement global : $UPTIME"
  overallUptimeTitle: Temps de fonctionnement global
  averageResponseTime: "Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Temps de réponse moyen
  sevelDayResponseTime: Délai de réponse de 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: Opérationnel
  down: Arrêt
  degraded: Degradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  rateLimitExceededTitle: Limite de taux dépassée
  rateLimitExceededIntro: Vous avez dépassé le nombre de requêtes que vous pouvez effectuer en une heure. Vous devrez donc attendre avant d'accéder à nouveau à ce site Web. Vous pouvez également ajouter un jeton d'accès personnel GitHub pour continuer à utiliser ce site Web.
  rateLimitExceededWhatDoesErrorMean: Que signifie cette erreur ?
  rateLimitExceededErrorMeaning: Ce site web utilise l'API GitHub pour accéder à des données en temps réel sur l'état de nos sites web. Par défaut, GitHub autorise à chaque adresse IP 60 requêtes par heure, que vous avez consommées.
  rateLimitExceededErrorHowCanFix: Comment puis-je le réparer ?
  rateLimitExceededErrorFix: Vous pouvez attendre une heure de plus et la limite de votre adresse IP sera rétablie. Vous pouvez également ajouter votre jeton d'accès personnel GitHub, qui vous donne droit à 5 000 demandes supplémentaires par heure.
  rateLimitExceededGeneratePAT: Apprenez comment générer un jeton d'accès personnel
  rateLimitExceededHasSet: Vous avez défini un jeton d'accès personnel.
  rateLimitExceededRemoveToken: Retiré le token
  rateLimitExceededGitHubPAT: Token d'accès personnel GitHub
  rateLimitExceededCopyPastePAT: Copiez et collez votre jeton
  rateLimitExceededSaveToken: Sauvegarder le token
  errorTitle: Une erreur s'est produite
  errorIntro: Une erreur s'est produite en essayant d'obtenir les derniers détails du statut.
  errorText: Vous pourrez réessayer dans quelques instants.
  errorHome: Aller à la page d'accueil
  pastScheduledMaintenance: Maintenances programmées terminées
  scheduledMaintenance: Maintenances programmées
  scheduledMaintenanceSummaryStarted: Démarré le $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Démarrés le $DATE pour $DURATION minutes
  startedAt: Démarré le
  startsAt: Démarrés le
  duration: Durée
  durationMin: $DURATION minutes
  incidentCompleted: Complété
  incidentScheduled: Programmé
