# Change these first
owner: gekki-beep # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: iFive
    url: https://ifive-community.fr
  - name: Panel
    url: https://ifive-community.fr/panel
  - name: Steam
    url: http://api.steampowered.com
  - name: iFive DarkRP
    check: "tcp-ping"
    url: 51.91.215.27
    port: 10014
  - name: iFive CW
    check: "tcp-ping"
    url: 51.91.215.27
    port: 10007
  - name: iFive DS
    check: "tcp-ping"
    url: 51.91.215.27
    port: 10010
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /status-page # where "repo" is your repository name
  name: Status Page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "Status Page - Yothann"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Page de statuts pour plusieurs projets
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
